layout_spectrum: 0.2706093
color:
  saturation: 0
  brandStrength: 0.242614
  lightness: 0.360215
  rhythmicContrast: 1
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
typography_spectrum: 0.2956989
name: Coachspk
