name: Coachspk
favicon: null
layout_spectrum: 0.2706093
typography_spectrum: 0.2956989
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Social Media Strategy+Playbook
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
  brandStrength: 0.242614
  lightness: 0.360215
  saturation: 0
  rhythmicContrast: 1
purpose: []
